### ISSUE TITLE
Set up database for users/inventory

### ISSUE THREAD

**Issue by jrec15** [rocketpastsix/atlworkforcedev#12]
Will need a user table, inventory table, and a relationship table for now.

**Comment by lilliemadali** [comment]
Work selfie

**Comment by rocketpastsix** [comment]
Do we want MongoDB or SQL? Since we are moving to Angular with SPA, Mongo makes sense, but PHP works great with SQL

**Comment by roastlechon** [comment]
SQL should be fine as long as it can spit out to json

**Comment by rocketpastsix** [comment]
yea we can get json from SQL

**Comment by jrec15** [comment]
Just set up a mysql database, and uploaded the structure sql dump to the repository. I followed the data that was given to me for the most part, though we may need to make changes in the future for any additional functionality. I also have imported all the content into the database and have that sql dump as well which I'd rather send out by email
